using System;
using System.IO;
using System.Linq;
using XLibur.Excel;

namespace XLibur.Report.Examples;

/// <summary>
/// Every feature that the file format can break, in one workbook, with a checklist for opening it in
/// Excel.
/// </summary>
/// <remarks>
/// <para>
/// This one is not for reading — the examples above are clearer, one thing each. It exists because a
/// handful of things about a generated workbook cannot be checked by any test in the suite: whether
/// Excel opens the file without offering to repair it, and whether what it then draws is what was meant.
/// The schema validator says the parts are well-formed, which is necessary and nowhere near sufficient —
/// ClosedXML.Report's issue #200 is a four-year history of pivot output Excel refuses to open, all of
/// it schema-valid.
/// </para>
/// <para>
/// So: run it, open the two files side by side, and work down the checklist it prints. It was a
/// throwaway script the first time; committing it makes the check repeatable rather than rebuilt from
/// scratch every time the write path is touched.
/// </para>
/// <para>
/// Covered: grouping with subtotals and an outline, merged group labels, a sort surviving the grouping,
/// a per-row formula, one conditional-formatting rule over a generated block, a picture below the range,
/// a chart series re-pointed, a pivot over a cell area re-pointed, a pivot over a table refreshed
/// without being re-pointed, and a pivot generated by the template.
/// </para>
/// </remarks>
public sealed class EverythingAtOnce : ReportExample
{
    /// <summary>A 1×1 black PNG, scaled up on the sheet — a placeholder logo that is visible.</summary>
    private const string BlackPixelPng =
        "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=";

    public override string Name => "EverythingAtOnce";

    public override string Summary =>
        "Every feature the file format can break, with a checklist for opening it in Excel.";

    protected override void BuildTemplate(IXLWorkbook workbook)
    {
        BuildSalesSheet(workbook);
        BuildDetailSheet(workbook);
        BuildDetailTableSheet(workbook);

        BuildPivotSheet(workbook, "PivotByArea", "ByArea", byTable: false,
            "Pivot over the plain cell area Detail!A4:C6 — the engine re-points it, then refreshes.");
        BuildPivotSheet(workbook, "PivotByTable", "ByTable", byTable: true,
            "Pivot over the table DetailTable — the table grows itself, so the engine only refreshes.");

        var generated = workbook.AddWorksheet("PivotGenerated");
        generated.Cell("A1").Value =
            "Empty in the template. <<Pivot>> on the Detail sheet builds a pivot at A3 over whatever "
            + "Detail turned out to hold.";
        generated.Cell("A1").Style.Font.SetBold();
        generated.Column(1).Width = 22;
        generated.Column(2).Width = 16;

        workbook.Worksheet("Sales").SetTabActive();
    }

    /// <summary>
    /// The human-readable report: a bound title, a range grouped by region with subtotals and an
    /// outline, merged region labels, a per-row formula, conditional colouring, and a picture below it
    /// all.
    /// </summary>
    private static void BuildSalesSheet(IXLWorkbook workbook)
    {
        var sheet = workbook.AddWorksheet("Sales");

        sheet.Cell("A1").Value = "{{ Company }} — sales for {{ Year }}";
        sheet.Range("A1:F1").Merge();
        sheet.Cell("A1").Style.Font.SetBold().Font.SetFontSize(16);

        sheet.Cell("A2").Value = "Generated {{ RunOn }} · green where a line beats {{ Target }}";
        sheet.Cell("A2").Style.Font.SetItalic().Font.SetFontColor(XLColor.Gray);

        Headings(sheet, 4, "Region", "Category", "Product", "Qty", "Unit price", "Line total");

        // Row 5 is the repeated row. The line total is a real formula, so the copies are re-pointed at
        // their own rows by the core library rather than by the report engine.
        sheet.Cell("A5").Value = "{{ item.Region }}";
        sheet.Cell("B5").Value = "{{ item.Category }}";
        sheet.Cell("C5").Value = "{{ item.Product }}";
        sheet.Cell("D5").Value = "{{ item.Quantity }}";
        sheet.Cell("E5").Value = "{{ item.UnitPrice }}";
        sheet.Cell("F5").FormulaA1 = "D5*E5";
        sheet.Cell("E5").Style.NumberFormat.Format = "#,##0.00";
        sheet.Cell("F5").Style.NumberFormat.Format = "#,##0.00";

        // Row 6 is the options row. Its styling is what every subtotal row takes, which is how a group
        // total ends up looking like the grand total.
        sheet.Cell("A6").Value = "<<Group merge>>";
        sheet.Cell("B6").Value = "<<Group>>";
        sheet.Cell("C6").Value = "<<Sort>>";
        sheet.Cell("D6").Value = "<<Sum>>";
        sheet.Cell("E6").Value = "Total";
        sheet.Cell("F6").Value = "<<Sum>>";
        sheet.Range("A6:F6").Style.Font.SetBold();
        sheet.Range("A6:F6").Style.Border.SetTopBorder(XLBorderStyleValues.Thin);
        sheet.Cell("F6").Style.NumberFormat.Format = "#,##0.00";

        // One rule in the template, and one rule in the output however many rows it generates — which
        // is the whole of the difference from ClosedXML.Report's issue #216.
        sheet.Range("F5:F5").AddConditionalFormat()
            .WhenGreaterThan(300)
            .Fill.SetBackgroundColor(XLColor.LightGreen);

        workbook.DefinedNames.Add("Items", sheet.Range("A5:F6"));

        sheet.Cell("A8").Value = "The black block below should sit under the generated rows, not over them.";

        using var image = new MemoryStream(Convert.FromBase64String(BlackPixelPng));
        sheet.AddPicture(image, "Logo").MoveTo(sheet.Cell("A10")).WithSize(140, 70);

        sheet.Columns(1, 6).Width = 14;
        sheet.Column(3).Width = 18;
    }

    /// <summary>
    /// A flat range — no grouping, so no subtotal rows to confuse a chart or a pivot — with a chart
    /// plotting it and the field tags for the generated pivot.
    /// </summary>
    private static void BuildDetailSheet(IXLWorkbook workbook)
    {
        var sheet = workbook.AddWorksheet("Detail");

        sheet.Cell("A1").Value = "Flat detail — the chart and two of the pivot sheets read this";
        sheet.Cell("A1").Style.Font.SetBold();

        Headings(sheet, 4, "Product", "Region", "Line total");

        sheet.Cell("A5").Value = "{{ item.Product }}";
        sheet.Cell("B5").Value = "{{ item.Region }}";
        sheet.Cell("C5").Value = "{{ item.Total }}";
        sheet.Cell("C5").Style.NumberFormat.Format = "#,##0.00";

        // Row 6 is the options row. Its tags describe the generated pivot; reading a tag strips its
        // text, so the row is still empty afterwards and is removed — which is what keeps the chart's
        // rows where the checklist expects them.
        sheet.Cell("A6").Value = "<<Page>>";
        sheet.Cell("B6").Value = "<<Row>>";
        sheet.Cell("C6").Value = "<<Data title=\"Total sold\">><<Pivot dest=\"PivotGenerated!A3\" name=\"Generated\">>";

        workbook.DefinedNames.Add("Rows", sheet.Range("A5:C6"));

        var chart = sheet.Charts.Add(XLChartType.ColumnClustered);
        chart.Title = "Line total by product";
        chart.Series.Add("Line total", "Detail!$C$5:$C$5", "Detail!$A$5:$A$5");
        chart.Position.SetColumn(5).SetRow(4);
        chart.SecondPosition.SetColumn(16).SetRow(26);

        sheet.Columns(1, 3).Width = 16;
    }

    /// <summary>The same flat range, but wrapped in an Excel table.</summary>
    /// <remarks>
    /// A table source exercises the branch a defined-name source takes — grows on its own, needs only
    /// the refresh. Setting a cache's source to a <em>name</em> is not on the public API, so in practice
    /// a template author does that in Excel rather than in code; the engine treats the two identically.
    /// </remarks>
    private static void BuildDetailTableSheet(IXLWorkbook workbook)
    {
        var sheet = workbook.AddWorksheet("DetailTable");

        sheet.Cell("A1").Value = "The same detail inside an Excel table — the PivotByTable sheet reads this";
        sheet.Cell("A1").Style.Font.SetBold();

        sheet.Cell("A4").Value = "Product";
        sheet.Cell("B4").Value = "Region";
        sheet.Cell("C4").Value = "Line total";

        sheet.Cell("A5").Value = "{{ item.Product }}";
        sheet.Cell("B5").Value = "{{ item.Region }}";
        sheet.Cell("C5").Value = "{{ item.Total }}";
        sheet.Cell("C5").Style.NumberFormat.Format = "#,##0.00";

        // The table spans the heading, the repeated row and the options row, so expansion inserting
        // below the repeated row lands inside it and the table grows.
        sheet.Range("A4:C6").CreateTable("DetailTable");

        workbook.DefinedNames.Add("TableRows", sheet.Range("A5:C6"));

        sheet.Columns(1, 3).Width = 16;
    }

    private static void BuildPivotSheet(
        IXLWorkbook workbook, string sheetName, string pivotName, bool byTable, string caption)
    {
        var sheet = workbook.AddWorksheet(sheetName);

        sheet.Cell("A1").Value = caption;
        sheet.Cell("A1").Style.Font.SetBold();

        var pivot = byTable
            ? sheet.PivotTables.Add(pivotName, sheet.Cell("A3"), workbook.Worksheet("DetailTable").Table("DetailTable"))
            : sheet.PivotTables.Add(pivotName, sheet.Cell("A3"), workbook.Worksheet("Detail").Range("A4:C6"));

        pivot.RowLabels.Add("Region");
        pivot.Values.Add("Line total");

        sheet.Column(1).Width = 22;
        sheet.Column(2).Width = 16;
    }

    protected override void AddData(IXLTemplate template)
    {
        var sales = SalesData.Sales();

        template.AddVariable("Company", "Contoso Ltd");
        template.AddVariable("Year", 2026);
        template.AddVariable("RunOn", new DateTime(2026, 7, 30).ToString("d MMMM yyyy"));
        template.AddVariable("Target", 300m);
        template.AddVariable("Items", sales);
        template.AddVariable("Rows", sales);
        template.AddVariable("TableRows", sales);
    }

    protected override void Describe(IXLWorkbook generated, TextWriter output)
    {
        WhatTheFileSays(generated, output);
        Checklist(output);
    }

    private static void WhatTheFileSays(IXLWorkbook workbook, TextWriter output)
    {
        var sales = workbook.Worksheet("Sales");
        var series = workbook.Worksheet("Detail").Charts.Single().Series.Single();

        output.WriteLine("  What the generated file says when read back");
        output.WriteLine("  ───────────────────────────────────────────");
        output.WriteLine($"    Sales, rows used           through row {sales.RangeUsed()!.RangeAddress.LastAddress.RowNumber}   (template: 10)");
        output.WriteLine($"    Sales, conditional formats {sales.ConditionalFormats.Count()}   (template: 1 — one per row would be the bug)");
        output.WriteLine($"    Sales, merged ranges       {sales.MergedRanges.Count}   (the title, plus one per region)");
        output.WriteLine($"    Sales, picture anchor      row {sales.Pictures.Single().TopLeftCell.Address.RowNumber}   (template: 10)");
        output.WriteLine($"    Sales, deepest outline     {sales.Rows().Max(row => row.OutlineLevel)}   (two group levels)");
        output.WriteLine($"    Chart value series         {series.ValueReferences}   (template: Detail!$C$5:$C$5)");
        output.WriteLine($"    Chart category series      {series.CategoryReferences}   (template: Detail!$A$5:$A$5)");
        output.WriteLine($"    Table DetailTable          {workbook.Worksheet("DetailTable").Table("DetailTable").RangeAddress}   (template: A4:C6)");
        output.WriteLine($"    Pivot caches               {workbook.PivotCaches.Count()}   (the generated pivot shares the re-pointed one)");

        foreach (var sheetName in new[] { "PivotByArea", "PivotByTable", "PivotGenerated" })
        {
            var pivot = workbook.Worksheet(sheetName).PivotTables.Single();

            output.WriteLine();
            output.WriteLine($"    {sheetName}, fields        {string.Join(", ", pivot.PivotCache.FieldNames)}");
            output.WriteLine($"    {sheetName}, refresh onopen {pivot.PivotCache.RefreshDataOnOpen}");
        }

        var built = workbook.Worksheet("PivotGenerated").PivotTables.Single();
        output.WriteLine();
        output.WriteLine($"    PivotGenerated, name       {built.Name}   (from name= on the tag)");
        output.WriteLine($"    PivotGenerated, at         {built.TargetCell.Address}   (from dest= on the tag)");
        output.WriteLine($"    PivotGenerated, rows       {string.Join(", ", built.RowLabels.Select(f => f.SourceName))}   (<<Row>> under Region)");
        output.WriteLine($"    PivotGenerated, filters    {string.Join(", ", built.ReportFilters.Select(f => f.SourceName))}   (<<Page>> under Product)");
        output.WriteLine($"    PivotGenerated, values     {string.Join(", ", built.Values.Select(v => $"{v.SummaryFormula} of {v.SourceName} as '{v.CustomName}'"))}");
        output.WriteLine();
    }

    private static void Checklist(TextWriter output)
    {
        output.WriteLine("  What to check in Excel");
        output.WriteLine("  ──────────────────────");
        output.WriteLine("    0. Both files open with NO repair dialog. This is the check no automated test");
        output.WriteLine("       can make, and the only reason this example exists.");
        output.WriteLine();
        output.WriteLine("    Sales sheet");
        output.WriteLine("    1. The outline buttons down the left collapse to region subtotals, and again to");
        output.WriteLine("       the grand total.");
        output.WriteLine("    2. Each region's label is merged over its rows.");
        output.WriteLine("    3. Subtotal rows are bold with a rule above — the same styling as the grand");
        output.WriteLine("       total, taken from the template's options row.");
        output.WriteLine("    4. Products read alphabetically inside each category: the sort survived the");
        output.WriteLine("       grouping that reordered the rows around it.");
        output.WriteLine("    5. Line totals over 300 are filled green. Then Home > Conditional Formatting >");
        output.WriteLine("       Manage Rules: exactly ONE rule, over the whole block.");
        output.WriteLine("    6. The grand total in F equals the sum of the twelve lines, not double it —");
        output.WriteLine("       SUBTOTAL ignores the region subtotals nested inside its range.");
        output.WriteLine("    7. The black block sits below every generated row, with its sentence above it.");
        output.WriteLine();
        output.WriteLine("    Detail sheet");
        output.WriteLine("    8. The chart shows TWELVE columns with product names along the axis. One column");
        output.WriteLine("       means the series was not re-pointed.");
        output.WriteLine("    9. Right-click the chart > Select Data: the ranges cover rows 5 to 16.");
        output.WriteLine();
        output.WriteLine("    Pivot sheets");
        output.WriteLine("   10. All three pivots show every region with its total, and the three agree.");
        output.WriteLine("   11. On each: right-click > PivotTable Options > Data — 'Refresh data when opening");
        output.WriteLine("       the file' is ticked.");
        output.WriteLine("   12. On each: PivotTable Analyze > Change Data Source — PivotByArea and");
        output.WriteLine("       PivotGenerated show the grown range, PivotByTable still shows the table name.");
        output.WriteLine("   13. PivotGenerated exists at all: the template has nothing on that sheet, and its");
        output.WriteLine("       Product filter and 'Total sold' column came from tags in Detail's options row.");
        output.WriteLine();
        output.WriteLine("    For contrast, open the template: one data row everywhere, a chart with a single");
        output.WriteLine("    column, and pivots over a single row of data.");
    }
}
