using System.IO;
using System.Linq;
using XLibur.Excel;

namespace XLibur.Report.Examples;

/// <summary>
/// The two ways to get a pivot table over generated data: draw one in the template, or let the template
/// generate one.
/// </summary>
/// <remarks>
/// <para>
/// <b>Drawn</b> is the one to reach for. Build the pivot in Excel over the template's data rows, lay it
/// out however the report wants, and the engine points it at what was generated and marks it to refresh
/// when the file is opened. The template author gets Excel's own pivot designer, and the engine has one
/// small job.
/// </para>
/// <para>
/// <b>Generated</b> is for a pivot whose shape belongs to the template rather than to the person who
/// drew it: <c>&lt;&lt;Pivot dest="..."&gt;&gt;</c> in the options row, with <c>&lt;&lt;Row&gt;&gt;</c>,
/// <c>&lt;&lt;Column&gt;&gt;</c>, <c>&lt;&lt;Page&gt;&gt;</c> and <c>&lt;&lt;Data&gt;&gt;</c> under the
/// columns it should use. Each field is named by its column's heading.
/// </para>
/// <para>
/// Both are here, over the same data, so the two can be read against each other. Their figures should
/// agree.
/// </para>
/// <para>
/// A pivot needs a heading row above the range, since that is where a pivot cache reads its field names
/// from — the same convention <c>&lt;&lt;AutoFilter&gt;&gt;</c> follows. And a pivot cannot be built
/// over a grouped range: the subtotal rows would be counted as data on top of the rows they already
/// total, so the engine refuses rather than quietly doubling everything.
/// </para>
/// </remarks>
public sealed class PivotOverGeneratedRows : ReportExample
{
    public override string Name => "Pivot";

    public override string Summary => "A pivot drawn in the template and one generated by it, over the same rows.";

    protected override void BuildTemplate(IXLWorkbook workbook)
    {
        var data = workbook.AddWorksheet("Data");

        data.Cell("A1").Value = "Flat data — both pivots read this";
        data.Cell("A1").Style.Font.SetBold();

        // Row 3 is the heading row, and it is not part of the range: it is where a pivot reads its
        // field names from.
        Headings(data, 3, "Region", "Category", "Line total");

        data.Cell("A4").Value = "{{ item.Region }}";
        data.Cell("B4").Value = "{{ item.Category }}";
        data.Cell("C4").Value = "{{ item.Total }}";
        data.Cell("C4").Style.NumberFormat.Format = "#,##0.00";

        // The options row says what the generated pivot is made of. Reading a tag strips its text, so
        // the row is still empty afterwards and is removed.
        data.Cell("A5").Value = "<<Row>>";
        data.Cell("B5").Value = "<<Column>>";
        data.Cell("C5").Value = "<<Data title=\"Sold\">><<Pivot dest=\"Generated!A3\" name=\"Generated\">>";

        workbook.DefinedNames.Add("Sales", data.Range("A4:C5"));
        data.Columns(1, 3).Width = 16;

        Drawn(workbook, data);
        GeneratedDestination(workbook);
    }

    /// <summary>The pivot a template author draws, over the template's own rows.</summary>
    private static void Drawn(IXLWorkbook workbook, IXLWorksheet data)
    {
        var sheet = workbook.AddWorksheet("Drawn");

        sheet.Cell("A1").Value = "Drawn in the template over Data!A3:C5 — re-pointed and refreshed.";
        sheet.Cell("A1").Style.Font.SetBold();

        // The source covers the heading row, the repeated row and the options row: exactly what a
        // template author would select. The engine grows it to cover what was generated.
        var pivot = sheet.PivotTables.Add("Drawn", sheet.Cell("A3"), data.Range("A3:C5"));
        pivot.RowLabels.Add("Region");
        pivot.ColumnLabels.Add("Category");
        pivot.Values.Add("Line total");

        sheet.Column(1).Width = 18;
        sheet.Columns(2, 4).Width = 14;
    }

    /// <summary>Where the generated pivot goes. Empty in the template, on purpose.</summary>
    private static void GeneratedDestination(IXLWorkbook workbook)
    {
        var sheet = workbook.AddWorksheet("Generated");

        sheet.Cell("A1").Value =
            "Empty in the template. <<Pivot>> on the Data sheet builds a pivot at A3 over whatever Data "
            + "turned out to hold.";
        sheet.Cell("A1").Style.Font.SetBold();

        sheet.Column(1).Width = 18;
        sheet.Columns(2, 4).Width = 14;
    }

    protected override void AddData(IXLTemplate template) =>
        template.AddVariable("Sales", SalesData.Sales());

    protected override void Describe(IXLWorkbook generated, TextWriter output)
    {
        foreach (var sheetName in new[] { "Drawn", "Generated" })
        {
            var pivot = generated.Worksheet(sheetName).PivotTables.Single();
            var rows = string.Join(", ", pivot.RowLabels.Select(field => field.SourceName));
            var values = string.Join(", ", pivot.Values.Select(value => $"{value.SummaryFormula} of {value.SourceName}"));

            output.WriteLine($"  {sheetName,-9}  at {pivot.TargetCell.Address}, rows: {rows}, values: {values}");
        }

        output.WriteLine();
        output.WriteLine("  In Excel: the two sheets show the same figures. On each, PivotTable Analyze >");
        output.WriteLine("  Change Data Source names the generated rows, and PivotTable Options > Data has");
        output.WriteLine("  'Refresh data when opening the file' ticked.");
    }
}
